# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 06:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AudioTrackGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_item', models.IntegerField()),
                ('order_description', models.CharField(max_length=3000)),
                ('order_time', models.DateField(auto_now=True)),
                ('total_amount', models.IntegerField()),
                ('delivered_flag', models.BooleanField()),
                ('cancelled_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('audio_track_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.AudioTrackDetail')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.OrderDetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtraDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='audio_track_detail',
            field=models.ManyToManyField(through='audio.OrderItemDetail', to='audio.AudioTrackDetail'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiotrackdetail',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.AudioTrackGenre'),
        ),
    ]
