# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20170912_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextradetail',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
